dataset:
  # Training_dataset: /NFS_home/NFS_home_6/dongkj/TCR/DataMerge/scRawCount/RawData3/processedData/KidneyData.h5ad
  # Training_profile_dist: /home/gaoyicheng/BM2_Projects/DalleTCR/IncompleteTripleModality/UniTCR/Kidney/Profile_dist.h5ad
  # Training_tcr_dist: /home/gaoyicheng/BM2_Projects/DalleTCR/tcr-bert/kidney/tcr_dist.h5ad
  Training_dataset: ./Data/Examples/Examples_Data.h5ad
  Training_profile_dist: ./Data/Examples/Examples_profile_dist.h5ad
  Training_tcr_dist: ./Data/Examples/Examples_tcr_dist.h5ad
Train:
  Sampling:
    batch_size: 256
    sample_shuffle: True
  
  Model_Parameter:
    encoderTCR_in_dim: 5
    encoderTCR_out_dim: 256
    encoderprofile_in_dim: 5000
    encoderprofile_hid_dim: 1024
    encoderprofile_hid_dim2: 512
    encoderprofle_out_dim: 256
    out_dim: 256
    head_num: 4
    device: cuda

  Trainer_parameter:
    random_seed: 888
    epoch: 150
    learning_rate: 0.0001
  
  output_dir: ./Experiments/TrainingResult_Pretrain

Inference:
  Sampling:
    batch_size: 256
    sample_shuffle: False
  Model: ./Experiments/TrainingResult_Pretrain/Model_checkpoints/epoch150_model.pth